dataset_path: /Users/ranhomri/tensorleap/data/coco-2017 # this foldr is expected to contain a json file for each subset and an `images` dir

TRAIN_SIZE: 8
VAL_SIZE: 8
TEST_SIZE: 8

BACKGROUND_LABEL: 2
CLASSES: 1
CLASS_ID: 0
CONF_THRESH: 0.35
TOP_K: 300
IMAGE_SIZE: [640, 640]
SCALE_TO_SIZE: 636
LOAD_UNION_CATEGORIES_IMAGES: true
MAX_BB_PER_IMAGE: 20
MODEL_FORMAT: inference
NMS_THRESH: 0.7
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
BOX_SIZES:
- - - 10
    - 13
  - - 16
    - 30
  - - 33
    - 23
- - - 30
    - 61
  - - 62
    - 45
  - - 59
    - 119
- - - 116
    - 90
  - - 156
    - 198
  - - 373
    - 326