dataset_path: /Users/ranhomri/tensorleap/data/coco-2017 # this foldr is expected to contain a json file for each subset and an `images` dir

BATCH_SIZE: 4
TRAIN_SIZE: 8
VAL_SIZE: 8
TEST_SIZE: 8

BACKGROUND_LABEL: 81

CLASSES: 80
CONF_THRESH: 0.35
IMAGE_SIZE: [640, 640]
SCALE_TO_SIZE: 636
LOAD_UNION_CATEGORIES_IMAGES: true
MAX_BB_PER_IMAGE: 20
MODEL_FORMAT: inference
NMS_THRESH: 0.5
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
