dataset_path: /Users/ranhomri/tensorleap/data/coco-2017 # this foldr is expected to contain a json file for each subset and an `images` dir

BATCH_SIZE: 4
TRAIN_SIZE: 16
VAL_SIZE: 16
TEST_SIZE: 16

BACKGROUND_LABEL: 81

CLASSES: 80
CONF_THRESH: 0.35
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
BOX_SIZES:
- - - 10
    - 13
  - - 16
    - 30
  - - 33
    - 23
- - - 30
    - 61
  - - 62
    - 45
  - - 59
    - 119
- - - 116
    - 90
  - - 156
    - 198
  - - 373
    - 326
IMAGE_SIZE: [640, 640]
LOAD_UNION_CATEGORIES_IMAGES: true
MAX_BB_PER_IMAGE: 20
MODEL_FORMAT: inference
NMS_THRESH: 0.5
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
